--- 
name: "Travelling Through the Cosmos"
description: |
  Scientists have determined the Great A'Tuin's gender at long last, unfortunately they put it inside the [Discworld Planetary Information System](http://$turtles) and then had a rather unfortunate meeting with Death. Sadly, the late scientists were pretty bad at web sites and budget cuts had meant that they had to make their own information system. Even worse, though they were smart they were, as so many scientists are, a little mad (and really bad at web design, if we hadn't mentioned it). We honestly have no idea what they were even trying to do with their system. Maybe you'll have better luck than we did.
  
  - The Management
flag: "MCA-DCE4D899"